services:
  desiot-server:
    build:
      dockerfile: Dockerfile-dev
      args:
        PORT: ${PORT}
    ports:
      - 7001:7001
    command: bash -c "(cd ./lib/src/chacha20poly1305/c_files/ && make clean && make all) && npm run dev"
    # bind mount
    volumes:
      - ./:/mern-app/server/
      - /mern-app/server/node_modules
