FROM node:18.14.2

WORKDIR /mern-app/server

COPY package.json .
# copy all component
COPY . .
RUN npm i --force
RUN npm i --workspaces --force
RUN apt update
RUN apt install build-essential
# RUN ["/bin/bash", "-c", "(cd ./lib/src/chacha20poly1305/c_files/ && make clean && make all)"]

# Listen port.
ARG PORT
EXPOSE $PORT

# Run CMD.
CMD ["(cd ./lib/src/chacha20poly1305/c_files/ && make clean && make all)", "&&", "npm", "run", "dev"]
