module.exports = Object.freeze({
  H1_DEFAULT: 0x7,
  H2_DEFAULT: 0x17,
  T1_DEFAULT: 0x7,
  T1_DEFAULT: 0x17,
  //
  H1_INDEX: 0,
  H2_INDEX: 1,
  CMD_INDEX: 2,
  DT_LEN_1_INDEX: 3,
  DT_LEN_2_INDEX: 4,
  DATA_START_INDEX: 5,

  //
  DT_LEN_MASK: 0x3ff,

  //
  DATA_LEN_SIZE: 2,
  CMD_SIZE: 1,
  GATEWAY_ID_SIZE: 12,

  // CMDs
  CMD_ASSIGN_VIRTUAL_STORAGE: 0,

  // DATA POS
  CONNECTION_TYPE_POS: 12,
  CONNECTION_ID_POS: 13,
});
