const H1_DEFAULT = 0x7;
const H2_DEFAULT = 0x17;
const T1_DEFAULT = 0x7;
const T2_DEFAULT = 0x17;
//
const H1_INDEX = 0;
const H2_INDEX = 1;
const CMD_INDEX = 2;
const DT_LEN_1_INDEX = 3;
const DT_LEN_2_INDEX = 4;
const DATA_START_INDEX = 5;

//
const DT_LEN_MASK = 0x3ff;

//
const DATA_LEN_SIZE = 2;
const CMD_SIZE = 1;
const GATEWAY_ID_SIZE = 25;
const CONFIG_ID_SIZE = 25;
const DEVICE_ID_SIZE = 25;

// CMDs
const CMD_DEVICE_ASSIGN_VIRTUAL_STORAGE = 0;

// DATA POS
const GATEWAY_ID_POS = 0;
const CONNECTION_TYPE_POS = GATEWAY_ID_POS + GATEWAY_ID_SIZE;
const CONNECTION_ID_POS = CONNECTION_TYPE_POS + 1;
const CONFIG_ID_POS = CONNECTION_ID_POS + 1;
const DEVICE_ID_POS = CONFIG_ID_POS + CONFIG_ID_SIZE; // plus config ID size.
const MAIN_DATA_START_POS = DEVICE_ID_POS + DEVICE_ID_SIZE;

//
const VS_TYPE_INT = 0;

module.exports = Object.freeze({
  H1_DEFAULT,
  H2_DEFAULT,
  T1_DEFAULT,
  T2_DEFAULT,
  //
  H1_INDEX,
  H2_INDEX,
  CMD_INDEX,
  DT_LEN_1_INDEX,
  DT_LEN_2_INDEX,
  DATA_START_INDEX,

  //
  DT_LEN_MASK,

  //
  DATA_LEN_SIZE,
  CMD_SIZE,
  GATEWAY_ID_SIZE,
  CONFIG_ID_SIZE,
  DEVICE_ID_SIZE,

  // CMDs
  CMD_DEVICE_ASSIGN_VIRTUAL_STORAGE,

  // DATA POS
  GATEWAY_ID_POS,
  CONNECTION_TYPE_POS,
  CONNECTION_ID_POS,
  CONFIG_ID_POS,
  DEVICE_ID_POS,
  MAIN_DATA_START_POS,

  // VS types
  VS_TYPE_INT,
});
